-- MySQL Script generated by MySQL Workbench
-- jue 15 nov 2018 13:35:22 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vivero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivero` (
  `Cord` POINT NOT NULL,
  `localidad` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cord`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `Cord` POINT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `producto` VARCHAR(45) NULL,
  PRIMARY KEY (`Cord`, `nombre`),
  CONSTRAINT `Cod`
    FOREIGN KEY (`Cord`)
    REFERENCES `mydb`.`Vivero` (`Cord`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `DNI` INT NOT NULL,
  `fecha_in` DATE NOT NULL,
  `sueldo` INT NULL,
  `css` VARCHAR(45) NULL,
  `producto` VARCHAR(45) NULL,
  `Cord` POINT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_fin` DATE NULL,
  `ventas` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`, `fecha_in`),
  INDEX `Cod_idx` (`Cord` ASC),
  INDEX `nombre_idx` (`nombre` ASC),
  CONSTRAINT `Cod`
    FOREIGN KEY (`Cord`)
    REFERENCES `mydb`.`Zona` (`Cord`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nombre`
    FOREIGN KEY (`nombre`)
    REFERENCES `mydb`.`Zona` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI` INT NOT NULL,
  `Bonificacion` VARCHAR(45) NULL,
  `total_ventas` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `Cod` INT NOT NULL,
  `stack` VARCHAR(45) NULL,
  `precio` INT NULL,
  PRIMARY KEY (`Cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto_Empleado_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto_Empleado_Cliente` (
  `DNI_e` INT NOT NULL,
  `DNI_C` INT NOT NULL,
  `Cod_p` INT NOT NULL,
  `Cant` INT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`DNI_e`, `DNI_C`, `Cod_p`),
  INDEX `DNI_C_idx` (`DNI_C` ASC),
  INDEX `Cod_p_idx` (`Cod_p` ASC),
  CONSTRAINT `DNI_e`
    FOREIGN KEY (`DNI_e`)
    REFERENCES `mydb`.`Empleado` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DNI_C`
    FOREIGN KEY (`DNI_C`)
    REFERENCES `mydb`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cod_p`
    FOREIGN KEY (`Cod_p`)
    REFERENCES `mydb`.`Producto` (`Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Vivero`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Vivero` (`Cord`, `localidad`, `Nombre`) VALUES (125.152, 'la laguna', 'Laguna');
INSERT INTO `mydb`.`Vivero` (`Cord`, `localidad`, `Nombre`) VALUES (223.625, 'Santa Cruz', 'Santa_cruz');
INSERT INTO `mydb`.`Vivero` (`Cord`, `localidad`, `Nombre`) VALUES (362.859, 'Candelaria', 'Candelaria');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Zona`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Zona` (`Cord`, `nombre`, `producto`) VALUES (125.152, 'zona 1', 'platanos');
INSERT INTO `mydb`.`Zona` (`Cord`, `nombre`, `producto`) VALUES (125.152, 'zona 2', 'mandarinas');
INSERT INTO `mydb`.`Zona` (`Cord`, `nombre`, `producto`) VALUES (223.625, 'almacen', NULL);
INSERT INTO `mydb`.`Zona` (`Cord`, `nombre`, `producto`) VALUES (362.859, 'zona 3', 'rosas');
INSERT INTO `mydb`.`Zona` (`Cord`, `nombre`, `producto`) VALUES (362.859, 'zona 4', 'geranios');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Empleado`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Empleado` (`DNI`, `fecha_in`, `sueldo`, `css`, `producto`, `Cord`, `nombre`, `fecha_fin`, `ventas`) VALUES (1111, '10-02-17', 1117, NULL, 'platano', 125.152, 'zona 1', NULL, '5');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Cliente`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Cliente` (`DNI`, `Bonificacion`, `total_ventas`) VALUES (2222, '0', '0');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Producto`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Producto` (`Cod`, `stack`, `precio`) VALUES (1234, '12', 15);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Producto_Empleado_Cliente`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Producto_Empleado_Cliente` (`DNI_e`, `DNI_C`, `Cod_p`, `Cant`, `fecha`) VALUES (1111, 2222, 1234, 0, '22-03-19');

COMMIT;

